#!/bin/bash
# modified by shazeya@syafi.com (NL130240)

./athena-start start
sleep 30

while [ true ]; do
    if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
#    if [ "      0" = "$(ps | grep -e login | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
       [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
        printf "Ошибка:"
        date
        sleep 10
        printf "Проверка:"
        date
        if [ "      0" = "$(ps | grep -e log | wc -l)" ] ||
#        if [ "      0" = "$(ps | grep -e login | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e char  | wc -l)" ] ||
           [ "      0" = "$(ps | grep -e map   | wc -l)" ]; then
            printf "Ошибка при проверке:"
            date
            printf "Восстановление:"
            date
            ./athena-start start
        else
            printf "Проверка пропущена:"
            date
        fi
#    else
#        printf "Проверка завершена:"
#        date
    fi
    sleep 10
done
